### ISSUE TITLE
GoldenHeads v2.1 (Is it up to date?)

### ISSUE THREAD

**Issue by Brasil150** [Kikisito/GoldenHeads#18] opened 2024-09-20 19:42 UTC
Hello, sorry but I think it will have to be opened again. The plugin still does not initialize.

```
[19:49:06 INFO]: [GoldenHeads] Enabling GoldenHeads v2.1
[19:49:06 INFO]: [GoldenHeads] Thanks for using GoldenHeads v2.1 by Kikisito.
[19:49:06 ERROR]: Error occurred while enabling GoldenHeads v2.1 (Is it up to date?)
java.lang.IllegalArgumentException: Can not set net.minecraft.world.item.component.ResolvableProfile field org.bukkit.craftbukkit.inventory.CraftMetaSkull.profile to com.mojang.authlib.GameProfile
        at java.base/jdk.internal.reflect.FieldAccessorImpl.throwSetIllegalArgumentException(FieldAccessorImpl.java:228) ~[?:?]
        at java.base/jdk.internal.reflect.FieldAccessorImpl.throwSetIllegalArgumentException(FieldAccessorImpl.java:232) ~[?:?]
        at java.base/jdk.internal.reflect.MethodHandleObjectFieldAccessorImpl.set(MethodHandleObjectFieldAccessorImpl.java:115) ~[?:?]
        at java.base/java.lang.reflect.Field.set(Field.java:836) ~[?:?]
        at goldenheads-2.1.jar/com.github.kikisito.goldenheads.GoldenHead.base64SkullBuilder(GoldenHead.java:105) ~[goldenheads-2.1.jar:?]
        at goldenheads-2.1.jar/com.github.kikisito.goldenheads.GoldenHead.createHead(GoldenHead.java:69) ~[goldenheads-2.1.jar:?]
        at goldenheads-2.1.jar/com.github.kikisito.goldenheads.Main.registerRecipe(Main.java:90) ~[goldenheads-2.1.jar:?]
        at goldenheads-2.1.jar/com.github.kikisito.goldenheads.Main.onEnable(Main.java:59) ~[goldenheads-2.1.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[purpur-1.21.1.jar:1.21.1-2308-8332fa4]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[purpur-1.21.1.jar:1.21.1-2308-8332fa4]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:654) ~[purpur-1.21.1.jar:1.21.1-2308-8332fa4]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:603) ~[purpur-1.21.1.jar:1.21.1-2308-8332fa4]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:758) ~[purpur-1.21.1.jar:1.21.1-2308-8332fa4]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:520) ~[purpur-1.21.1.jar:1.21.1-2308-8332fa4]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:366) ~[purpur-1.21.1.jar:1.21.1-2308-8332fa4]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1231) ~[purpur-1.21.1.jar:1.21.1-2308-8332fa4]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:334) ~[purpur-1.21.1.jar:1.21.1-2308-8332fa4]
        at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
[19:49:06 INFO]: [GoldenHeads] Disabling GoldenHeads v2.1
```

**Comment by Brasil150** [comment] 2024-09-21 14:04
I have already tried downloading the Jar again and the problem persists.

**Comment by TymekSL** [comment] 2024-10-10 17:19
I have same problem !!!!!!!!

**Comment by Brasil150** [comment] 2024-10-10 21:17
> I have same problem !!!!!!!!

I also still have this mentioned issue, I'm not using the latest version because of this. I'm using a version that was compiled in the last open issue. The download is there. But remember that it is not the latest version as it causes this problem.

**Comment by TymekSL** [comment] 2024-10-13 17:08
> > I have same problem !!!!!!!!
> 
> I also still have this mentioned issue, I'm not using the latest version because of this. I'm using a version that was compiled in the last open issue. The download is there. But remember that it is not the latest version as it causes this problem.

if i understand correctly you using GoldenHeads 2.0 and it work yes? Because 2.1 make those problems and author ignore us

**Comment by TymekSL** [comment] 2024-10-21 22:16
> Hello. I am not able to reproduce this issue with the jar in the _Releases_ page. Are you using online mode?

i have same problem so dont say you cant reproduce the issue lamo

**Comment by TymekSL** [comment] 2024-11-13 22:49
i have same problem so dont say you cant reproduce the issue lamo

**Comment by TymekSL** [comment] 2024-11-13 22:49
THANKS FOR IGNORING BUGS BRO

**Comment by Reddishye** [comment] 2024-11-14 15:07
Sorry for the delay with this issue, I had no time to fix it, however it will be fixed today as I got enough time to fix it.

**Comment by TymekSL** [comment] 2024-11-17 22:21
> Sorry for the delay with this issue, I had no time to fix it, however it will be fixed today as I got enough time to fix it.

mhm

**Comment by TymekSL** [comment] 2024-11-17 22:22
thanks for deleting all my comments ;p you are really weird 0 hgelp 0 updates 0 fixes

**Comment by TymekSL** [comment] 2024-11-17 22:22
**yea. remove my coments here you are i won't remove review**

**Comment by Kikisito** [comment] 2024-11-18 09:51
> **yea. remove my coments here you are i won't remove review**

Your comments have been deleted because they aren’t helpful in any way and you are just trying to make things worse. You won’t be allowed to answer anymore as I reported and blocked you. We don’t mind about your Spigot review.

@Reddishye is already working on a fix and asap he will upload it.

**Comment by Reddishye** [comment] 2024-11-18 15:19
@Brasil150 may I have your configuration file? I'm being unable to reproduce it with a compiled version.

**Comment by Reddishye** [comment] 2024-11-18 15:19
@Brasil150 may I have your configuration file? I'm being unable to reproduce it with a compiled version.

**Comment by Reddishye** [comment] 2024-11-18 15:21
Also, may I know If your server is online or offline mode? The issue seems to be related with skulls.

**Comment by Brasil150** [comment] 2024-11-18 17:15
`# Welcome to the GoldenHeads configuration file!

debug: false
golden-heads:
  material: PLAYER_HEAD
  delay: 0
  food-amount: 6
  saturation-amount: 14.4
  skull-owner: PhantomTupac
  display-name: '&6Cabeça Dourada'
  lore:
  - '&eAbsorption II (2:00)'
  - '&eRegeneration III (0:02)'
  - '&eFire Resistance (0:10)'
  potion-effects:
  - ABSORPTION|120|2
  - REGENERATION|2|3
  - FIRE_RESISTANCE|10|1
  custom-model-data: 1
  click-type: RIGHT_CLICK
  skull-texture: e3RleHR1cmVzOntTS0lOOnt1cmw6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvY2ZkMjdkOGIyMThiNWFhOTcyZmRhOTA1NDkyNmQ3YjFiMmMwMzI5YTQ1NjMzMjE0OGZjYzNkNmM2ZDM0Y2YwZiJ9fX0=
recipe:
  shape:
  - GGG
  - GPG
  - GGG
  ingredients:
    P: PLAYER_HEAD
    G: GOLD_INGOT
drop-player-head-on-death: false
drop-head-only-when-killed-by-a-player: true
messages:
  no-permission: '&cVocê não tem permissão para executar este comando.'
  player-not-found: '&cJogador não encontrado: %s'
  invalid-amount: '&cQuantidade inválida. Informe um número válido.'
  inventory-full: '&eSeu inventário está cheio. A cabeça dourada foi dropada no chão.'
  gave-to-all: '&aGave %d golden head(s) to all online players.'
  gave-to-player: '&aGave %d golden head(s) to %s.'
  give-usage: '&cUsage: /gheads give <*/player> [amount]'
  no-args: |-
    &6GoldenHeads &7v%s
    &7Author: &6Kikisito
    &7Commands:
    &6/gheads reload &7- Reload the configuration file.
    &6/gheads get &7- Get a golden head.
    &6/gheads give &7- Give a golden head to a player.
  invalid-player: '&cJogador inválido. Por favor utilize um nome válido.'
  only-player: '&cEsse comando só pode ser executado por um jogador.'
  got-golden-head: '&aYou have received a Golden Head!'
  reload-config: '&aGoldenHeads configuration reloaded successfully.'
  is-outdated: '&4&l[DESATUALIZADO]'
`

**Comment by Brasil150** [comment] 2024-11-18 17:15
Offline-mode

**Comment by Reddishye** [comment] 2024-11-18 19:31
Thanks, I'll check it right now.

**Comment by Brasil150** [comment] 2024-11-30 02:46
Hi @Reddishye any news about this?

**Comment by Brasil150** [comment] 2024-12-21 00:19
Hello. I beg you to shed some light on this. Can I try to provide some more information that may help you replicate the problem?

You could try using:
Purpur 1.21.1-2329-803bf62
Java 21

Some plugins that are currently being used on the server:
ProtocolLib, GoldenHeads, NBTAPI, packetevents, PlaceholderAPI, ViaVersion, ViaBackwards, FastAsyncWorldEdit, SystemChat, XConomy, CoreProtect, BungeeGuard, Floodgate, Vault, Multiverse-core

The server is running in Offline-Mode + Floodgate

**Comment by Kikisito** [comment] 2024-12-21 01:02
> Hello. I beg you to shed some light on this. Can I try to provide some more information that may help you replicate the problem?
> 
> You could try using: Purpur 1.21.1-2329-803bf62 Java 21
> 
> Some plugins that are currently being used on the server: ProtocolLib, GoldenHeads, NBTAPI, packetevents, PlaceholderAPI, ViaVersion, ViaBackwards, FastAsyncWorldEdit, SystemChat, XConomy, CoreProtect, BungeeGuard, Floodgate, Vault, Multiverse-core
> 
> The server is running in Offline-Mode + Floodgate

Hi, I managed to get some free time (this is just incredible) and I recoded the method that was failing. I'm sorry you had to wait for so long.

Can you try this build? It seems to work fine in my test server.

[goldenheads-2.1.zip](https://github.com/user-attachments/files/18216701/goldenheads-2.1.zip)

**Comment by Kikisito** [comment] 2024-12-21 01:04
> > Hello. I beg you to shed some light on this. Can I try to provide some more information that may help you replicate the problem?
> > You could try using: Purpur 1.21.1-2329-803bf62 Java 21
> > Some plugins that are currently being used on the server: ProtocolLib, GoldenHeads, NBTAPI, packetevents, PlaceholderAPI, ViaVersion, ViaBackwards, FastAsyncWorldEdit, SystemChat, XConomy, CoreProtect, BungeeGuard, Floodgate, Vault, Multiverse-core
> > The server is running in Offline-Mode + Floodgate
> 
> Hi, I managed to get some free time (this is just incredible) and I recoded the method that was failing. I'm sorry you had to wait for so long.
> 
> Can you try this build? It seems to work fine in my test server.
> 
> [goldenheads-2.1.zip](https://github.com/user-attachments/files/18216701/goldenheads-2.1.zip)

I forgot to say that you need to change the "skullTexture" in your configuration file as now it uses a normal url instead of a base64 string. Please, set it at `https://textures.minecraft.net/texture/cfd27d8b218b5aa972fda9054926d7b1b2c0329a456332148fcc3d6c6d34cf0f` (or your preferred texture)

**Comment by Brasil150** [comment] 2024-12-21 02:56
Hello, thank you for your quick response, I appreciate your attention to this issue. I will be testing it as soon as possible. And again, thank you.

**Comment by Brasil150** [comment] 2024-12-22 22:00
Apparently it solved the problem.
![image](https://github.com/user-attachments/assets/5e4371f3-c5b8-4382-98c6-8842011ddaa7)

**Comment by Kikisito** [comment] 2024-12-22 23:35
Thanks for your feedback. As it seems to be working fine, I'm closing the issue. If there is any problem, please open a new issue. And again, sorry for the delay.

**Closed by Kikisito** 2024-12-22 23:35 UTC
Labels: bug
